[build]
  publish = "site"
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    X-Robots-Tag = "noindex, nofollow"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "no-cache"
